#!/bin/bash

# Quick Start Guide for Study Resource Hub with Vault

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Study Resource Hub - Quick Start with HashiCorp Vault     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Prerequisites:"
echo "   ✓ Docker and Docker Compose installed"
echo "   ✓ All environment files configured"
echo "   ✓ Network connectivity available"
echo ""

echo "🚀 Starting the Application..."
echo ""
echo "Step 1: Build and start all services"
echo "$ docker-compose up --build"
echo ""
echo "This will:"
echo "   1. Start Vault server on http://localhost:8200"
echo "   2. Initialize Vault with AppRole authentication"
echo "   3. Start backend server on http://localhost:5000"
echo "   4. Start frontend on http://localhost:3000"
echo "   5. Configure nginx reverse proxy"
echo ""

echo "🔐 Vault Access:"
echo "   URL: http://localhost:8200/ui"
echo "   Token: root (development only)"
echo ""

echo "📊 Application URLs:"
echo "   Frontend: http://localhost:3000"
echo "   Backend API: http://localhost:5000/api"
echo "   Vault UI: http://localhost:8200/ui"
echo "   Nginx: http://localhost (http://localhost:443 for https)"
echo ""

echo "📝 Useful Commands:"
echo ""
echo "View Vault Status:"
echo "$ docker exec vault_server vault status"
echo ""
echo "View Stored Secrets:"
echo "$ docker exec vault_server vault login -method=token token=root"
echo "$ docker exec vault_server vault kv get secret/app/backend"
echo ""
echo "View Backend Logs:"
echo "$ docker logs backend_resource"
echo ""
echo "View Vault Agent Logs:"
echo "$ docker logs backend_resource | grep 'Vault Agent'"
echo ""
echo "Access Backend Container:"
echo "$ docker exec -it backend_resource sh"
echo ""
echo "Verify Secrets Loaded:"
echo "$ docker exec backend_resource cat /vault/secrets/backend.env"
echo ""

echo "🔍 Troubleshooting:"
echo ""
echo "If backend fails to start:"
echo "1. Check Vault is healthy: docker exec vault_server vault status"
echo "2. Check Vault Init completed: docker logs vault_init"
echo "3. Check AppRole credentials exist: docker exec vault_server ls /vault/secrets/"
echo "4. Check backend logs: docker logs backend_resource"
echo ""

echo "📚 For detailed documentation, see VAULT_SETUP.md"
echo ""
echo "═════════════════════════════════════════════════════════════"
